name-template: 'Meshery MCP Server v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'kind/feature'
      - 'kind/enhancement'
  - title: '🛠 MCP Tools, Resources, Prompts'
    labels:
      - 'component/tools'
      - 'component/resources'
      - 'component/prompts'
  - title: '🔌 Meshery Client'
    labels:
      - 'component/meshery-client'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/fix'
      - 'kind/bugfix'
      - 'kind/bug'
  - title: '🧰 Maintenance'
    labels:
      - 'kind/chore'
      - 'area/ci'
      - 'area/tests'
  - title: 📖 Documentation
    label: area/docs
  - title: 🔒 Security
    label: security
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's New
  ## 🔤 General
  $CHANGES

  ## 👨🏽‍💻 Contributors

  Thank you to our contributors for making this release possible:
  $CONTRIBUTORS
autolabeler:
  - label: 'area/docs'
    branch:
      - '/docs/'
  - label: 'area/ci'
    files:
      - '.github/**'
